name: payments_app
description: Flutter app for managing recurring payments (web + mobile).
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Routing
  go_router: ^14.2.1

  # HTTP client
  dio: ^5.5.0

  # State management
  flutter_riverpod: ^2.5.1
  logger: ^2.3.0

  # Storage (secure on mobile, shared_preferences on web)
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2

  # File picker & open files
  file_picker: ^8.1.2
  open_filex: ^4.5.0

  # JSON utils
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # UI
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  fl_chart: ^0.69.0

  # Misc
  path: ^1.9.0
  url_launcher: ^6.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true